import type { Announcement, EnrollmentRequest, AnnouncementType } from "@/components/features/enrollments/enrollments-types"

// ─── Available Programs ──────────────────────────────────────────────────────

export const AVAILABLE_PROGRAMS = [
  { id: 1,  title: "تطوير تطبيقات الويب المتقدمة",        type: "دورة" as AnnouncementType },
  { id: 2,  title: "إدارة المشاريع الاحترافية PMP",        type: "دورة" as AnnouncementType },
  { id: 3,  title: "التفكير الإبداعي وحل المشكلات",        type: "ورشة عمل" as AnnouncementType },
  { id: 4,  title: "المحاسبة المالية المتقدمة",             type: "دورة" as AnnouncementType },
  { id: 5,  title: "أمن المعلومات والحماية الرقمية",        type: "ورشة عمل" as AnnouncementType },
  { id: 6,  title: "الذكاء الاصطناعي والتعلم الآلي",       type: "دورة" as AnnouncementType },
  { id: 7,  title: "مهارات التواصل الفعّال",               type: "ورشة عمل" as AnnouncementType },
  { id: 8,  title: "القانون التجاري والعقود",               type: "دورة" as AnnouncementType },
  { id: 9,  title: "السلامة والصحة المهنية",                type: "ورشة عمل" as AnnouncementType },
  { id: 10, title: "إدارة الوقت والأولويات",               type: "ورشة عمل" as AnnouncementType },
  { id: 11, title: "تحليل البيانات باستخدام Python",       type: "دورة" as AnnouncementType },
  { id: 12, title: "إدارة الموارد البشرية",                 type: "دورة" as AnnouncementType },
]

// ─── Announcements ───────────────────────────────────────────────────────────

export const DUMMY_ANNOUNCEMENTS: Announcement[] = [
  { id: 1,  title: "تطوير تطبيقات الويب",                  type: "دورة",      instructor: "أحمد الكاظمي",   category: "تقنية",       duration: "40 ساعة",  startDate: "2025-04-10", endDate: "2025-05-10", location: "قاعة التدريب 1",   capacity: 30, registered: 18, description: "دورة شاملة في تطوير تطبيقات الويب باستخدام أحدث التقنيات والأُطر البرمجية.", status: "مفتوح", linkedProgramId: 1,    linkedProgramTitle: "تطوير تطبيقات الويب المتقدمة" },
  { id: 2,  title: "إدارة المشاريع الاحترافية PMP",        type: "دورة",      instructor: "سارة العلي",      category: "إدارية",      duration: "30 ساعة",  startDate: "2025-04-15", endDate: "2025-05-15", location: "قاعة المؤتمرات",    capacity: 25, registered: 22, description: "برنامج تدريبي معتمد للحصول على شهادة PMP.", status: "مفتوح", linkedProgramId: 2,    linkedProgramTitle: "إدارة المشاريع الاحترافية PMP" },
  { id: 3,  title: "التفكير الإبداعي وحل المشكلات",        type: "ورشة عمل",  instructor: "نور الهاشمي",    category: "تطوير ذاتي", duration: "3 ساعات",  startDate: "2025-04-20", endDate: "2025-04-20", location: "قاعة التدريب 2",   capacity: 20, registered: 8,  description: "ورشة عمل تفاعلية لتطوير مهارات التفكير الإبداعي.", status: "مفتوح", linkedProgramId: 3,    linkedProgramTitle: "التفكير الإبداعي وحل المشكلات" },
  { id: 4,  title: "المحاسبة المالية المتقدمة",             type: "دورة",      instructor: "محمد الحسيني",   category: "مالية",       duration: "20 ساعة",  startDate: "2025-05-01", endDate: "2025-05-20", location: "قاعة التدريب 1",   capacity: 20, registered: 15, description: "دورة متقدمة في المحاسبة المالية وفقاً للمعايير الدولية.", status: "مفتوح", linkedProgramId: 4,    linkedProgramTitle: "المحاسبة المالية المتقدمة" },
  { id: 5,  title: "أمن المعلومات للموظفين",               type: "ورشة عمل",  instructor: "علي الموسوي",    category: "تقنية",       duration: "3 ساعات",  startDate: "2025-04-25", endDate: "2025-04-25", location: "مختبر الحاسوب",     capacity: 30, registered: 12, description: "ورشة توعوية حول أساسيات أمن المعلومات وحماية البيانات.", status: "مفتوح", linkedProgramId: 5,    linkedProgramTitle: "أمن المعلومات والحماية الرقمية" },
  { id: 6,  title: "الذكاء الاصطناعي والتعلم الآلي",       type: "دورة",      instructor: "فاطمة الموسوي",  category: "تقنية",       duration: "50 ساعة",  startDate: "2025-05-10", endDate: "2025-06-20", location: "مختبر الحاسوب",     capacity: 20, registered: 19, description: "دورة تأسيسية في الذكاء الاصطناعي والتعلم العميق.", status: "مفتوح", linkedProgramId: 6,    linkedProgramTitle: "الذكاء الاصطناعي والتعلم الآلي" },
  { id: 7,  title: "مهارات التواصل الفعّال",               type: "ورشة عمل",  instructor: "زينب العامري",   category: "تطوير ذاتي", duration: "4 ساعات",  startDate: "2025-05-05", endDate: "2025-05-05", location: "القاعة الرئيسية",   capacity: 40, registered: 25, description: "ورشة عمل لتطوير مهارات التواصل الشفهي والكتابي.", status: "مفتوح", linkedProgramId: 7,    linkedProgramTitle: "مهارات التواصل الفعّال" },
  { id: 8,  title: "القانون التجاري والعقود",               type: "دورة",      instructor: "حسن الربيعي",    category: "قانونية",     duration: "25 ساعة",  startDate: "2025-05-15", endDate: "2025-06-05", location: "قاعة المؤتمرات",    capacity: 20, registered: 20, description: "دورة متخصصة في القانون التجاري وصياغة العقود.", status: "مغلق", linkedProgramId: 8,    linkedProgramTitle: "القانون التجاري والعقود" },
  { id: 9,  title: "السلامة والصحة المهنية",                type: "ورشة عمل",  instructor: "عمر الشمري",     category: "صحة وسلامة", duration: "3 ساعات",  startDate: "2025-04-28", endDate: "2025-04-28", location: "القاعة الرئيسية",   capacity: 50, registered: 30, description: "ورشة توعوية حول إجراءات السلامة والصحة المهنية.", status: "مفتوح", linkedProgramId: 9,    linkedProgramTitle: "السلامة والصحة المهنية" },
  { id: 10, title: "إدارة الوقت والأولويات",               type: "ورشة عمل",  instructor: "ريم السعدي",     category: "إدارية",      duration: "3 ساعات",  startDate: "2025-05-08", endDate: "2025-05-08", location: "غرفة الاجتماعات أ", capacity: 15, registered: 10, description: "ورشة عمل تطبيقية لتعلم أساليب إدارة الوقت.", status: "مفتوح", linkedProgramId: 10,   linkedProgramTitle: "إدارة الوقت والأولويات" },
  { id: 11, title: "تحليل البيانات باستخدام Python",       type: "دورة",      instructor: "أحمد الكاظمي",   category: "تقنية",       duration: "35 ساعة",  startDate: "2025-06-01", endDate: "2025-07-01", location: "مختبر الحاسوب",     capacity: 25, registered: 5,  description: "دورة عملية في تحليل البيانات باستخدام Python وأدواتها.", status: "مفتوح", linkedProgramId: 11,   linkedProgramTitle: "تحليل البيانات باستخدام Python" },
  { id: 12, title: "إدارة الموارد البشرية",                 type: "دورة",      instructor: "سارة العلي",      category: "إدارية",      duration: "20 ساعة",  startDate: "2025-06-10", endDate: "2025-06-25", location: "قاعة التدريب 1",   capacity: 20, registered: 0,  description: "دورة في أساسيات إدارة الموارد البشرية الحديثة.", status: "مفتوح", linkedProgramId: null, linkedProgramTitle: "" },
]

// ─── Enrollment Requests ─────────────────────────────────────────────────────

export const DUMMY_REQUESTS: EnrollmentRequest[] = [
  { id: 1,  announcementId: 1,  announcementTitle: "تطوير تطبيقات الويب",                announcementType: "دورة",     employeeName: "يوسف الخزاعي",  employeeDepartment: "تقنية المعلومات",  requestDate: "2025-03-18", status: "قيد المراجعة", notes: "الموظف مهتم بتطوير مهاراته البرمجية", reviewedBy: "",       reviewDate: "" },
  { id: 2,  announcementId: 1,  announcementTitle: "تطوير تطبيقات الويب",                announcementType: "دورة",     employeeName: "باسم العمارة",   employeeDepartment: "تقنية المعلومات",  requestDate: "2025-03-18", status: "مقبول",         notes: "",                                    reviewedBy: "المشرف", reviewDate: "2025-03-19" },
  { id: 3,  announcementId: 2,  announcementTitle: "إدارة المشاريع الاحترافية PMP",      announcementType: "دورة",     employeeName: "سارة العلي",     employeeDepartment: "الموارد البشرية",  requestDate: "2025-03-17", status: "مقبول",         notes: "ترشيح من مدير القسم",                reviewedBy: "المشرف", reviewDate: "2025-03-18" },
  { id: 4,  announcementId: 3,  announcementTitle: "التفكير الإبداعي وحل المشكلات",      announcementType: "ورشة عمل", employeeName: "كريم البغدادي",  employeeDepartment: "المالية",          requestDate: "2025-03-17", status: "قيد المراجعة", notes: "يرغب في تطوير مهارات حل المشكلات",    reviewedBy: "",       reviewDate: "" },
  { id: 5,  announcementId: 4,  announcementTitle: "المحاسبة المالية المتقدمة",           announcementType: "دورة",     employeeName: "هدى النجفي",     employeeDepartment: "التسويق",          requestDate: "2025-03-16", status: "مرفوض",         notes: "",                                    reviewedBy: "المشرف", reviewDate: "2025-03-17" },
  { id: 6,  announcementId: 5,  announcementTitle: "أمن المعلومات للموظفين",             announcementType: "ورشة عمل", employeeName: "علي الجبوري",    employeeDepartment: "الشؤون القانونية", requestDate: "2025-03-16", status: "قيد المراجعة", notes: "",                                    reviewedBy: "",       reviewDate: "" },
  { id: 7,  announcementId: 6,  announcementTitle: "الذكاء الاصطناعي والتعلم الآلي",     announcementType: "دورة",     employeeName: "نور الهاشمي",    employeeDepartment: "العمليات",         requestDate: "2025-03-15", status: "مقبول",         notes: "ذو خبرة تقنية",                       reviewedBy: "المشرف", reviewDate: "2025-03-16" },
  { id: 8,  announcementId: 7,  announcementTitle: "مهارات التواصل الفعّال",             announcementType: "ورشة عمل", employeeName: "حسن الربيعي",    employeeDepartment: "خدمة العملاء",     requestDate: "2025-03-15", status: "قيد المراجعة", notes: "يحتاج لتطوير مهارات التواصل مع العملاء", reviewedBy: "",    reviewDate: "" },
  { id: 9,  announcementId: 2,  announcementTitle: "إدارة المشاريع الاحترافية PMP",      announcementType: "دورة",     employeeName: "مريم الطائي",    employeeDepartment: "الموارد البشرية",  requestDate: "2025-03-14", status: "ملغي",          notes: "تم الإلغاء بطلب من الموظف",           reviewedBy: "",       reviewDate: "" },
  { id: 10, announcementId: 9,  announcementTitle: "السلامة والصحة المهنية",              announcementType: "ورشة عمل", employeeName: "لمياء الحلي",    employeeDepartment: "العمليات",         requestDate: "2025-03-14", status: "قيد المراجعة", notes: "",                                    reviewedBy: "",       reviewDate: "" },
  { id: 11, announcementId: 1,  announcementTitle: "تطوير تطبيقات الويب",                announcementType: "دورة",     employeeName: "طارق البصري",    employeeDepartment: "خدمة العملاء",     requestDate: "2025-03-13", status: "مرفوض",         notes: "التخصص غير مناسب",                    reviewedBy: "المشرف", reviewDate: "2025-03-14" },
  { id: 12, announcementId: 10, announcementTitle: "إدارة الوقت والأولويات",             announcementType: "ورشة عمل", employeeName: "دعاء الكوفي",    employeeDepartment: "الإدارة العليا",   requestDate: "2025-03-13", status: "مقبول",         notes: "",                                    reviewedBy: "المشرف", reviewDate: "2025-03-14" },
  { id: 13, announcementId: 3,  announcementTitle: "التفكير الإبداعي وحل المشكلات",      announcementType: "ورشة عمل", employeeName: "رائد السماوي",   employeeDepartment: "العمليات",         requestDate: "2025-03-12", status: "قيد المراجعة", notes: "",                                    reviewedBy: "",       reviewDate: "" },
  { id: 14, announcementId: 6,  announcementTitle: "الذكاء الاصطناعي والتعلم الآلي",     announcementType: "دورة",     employeeName: "سامر الكربلائي", employeeDepartment: "الشؤون القانونية", requestDate: "2025-03-12", status: "مرفوض",         notes: "القسم غير ذي صلة",                    reviewedBy: "المشرف", reviewDate: "2025-03-13" },
  { id: 15, announcementId: 4,  announcementTitle: "المحاسبة المالية المتقدمة",           announcementType: "دورة",     employeeName: "جاسم الموصلي",   employeeDepartment: "المالية",          requestDate: "2025-03-11", status: "مقبول",         notes: "ترشيح من مدير المالية",               reviewedBy: "المشرف", reviewDate: "2025-03-12" },
]
